---
all:
  vars:
      ansible_port: 22
      ansible_user: 'ukaul' 
      ansible_ssh_private_key_file: '/home/ukaul/.ssh/id_rsa'

control:
  hosts:
    shambu:
      ansible_connection: "local"
      ansible_python_interpreter: "/usr/bin/python3"

nodes:
  hosts:
    chef-node1:
      ansible_port: 22
ws:
  hosts:
    chef-ws1:
      
servers:
  hosts: 
    chef-server:
...
